# Generated by Django 3.2 on 2022-08-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_block', models.IntegerField()),
                ('price_square_meter', models.IntegerField()),
                ('count_entrance', models.IntegerField()),
                ('count_floors', models.IntegerField()),
                ('apartment_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_sale', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Выкуп', 'Выкуп'), ('Выкуп не до конца', 'Выкуп не до конца'), ('Расторгнуто', 'Расторгнуто'), ('Не продано', 'Не продано')], max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('apart_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.block')),
            ],
        ),
    ]
