# Generated by Django 3.2 on 2022-08-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apart_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complex.block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='date_of_sale',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата продажи'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО владельца квартиры'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('Выкуп', 'Выкуп'), ('Выкуп не до конца', 'Выкуп не до конца'), ('Расторгнуто', 'Расторгнуто'), ('Не продано', 'Не продано')], max_length=100, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='block',
            name='apartment_count',
            field=models.IntegerField(verbose_name='Количество квартир на этаж'),
        ),
        migrations.AlterField(
            model_name='block',
            name='count_entrance',
            field=models.IntegerField(verbose_name='Количество подъездов'),
        ),
        migrations.AlterField(
            model_name='block',
            name='count_floors',
            field=models.IntegerField(verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='block',
            name='number_block',
            field=models.CharField(max_length=100, verbose_name='Номер блока'),
        ),
        migrations.AlterField(
            model_name='block',
            name='price_square_meter',
            field=models.CharField(max_length=100, verbose_name='Стоимость за квадратный метр квартиры'),
        ),
    ]
