# Generated by Django 3.2 on 2022-08-21 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0003_alter_apartment_date_of_sale'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apartment',
            new_name='Client',
        ),
    ]
