# Generated by Django 3.2 on 2022-08-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0004_rename_apartment_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='apart_block',
            new_name='client_block',
        ),
    ]
