# Generated by Django 3.2 on 2022-08-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0005_rename_apart_block_client_client_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.IntegerField(verbose_name='Общая площадь'),
        ),
    ]
